### ISSUE TITLE
Release of pre-trained weights

### ISSUE THREAD

**Issue by AditTuf** [Jichen66/Master_Thesis#2]
Hi Jinchen66 can you please provide pre trained weights to your model if possible .A drive link will work or i can also provide you with my email ID so maybe you can mail them to  me

**Comment by JichenGuo** [comment]
Hi, the pre trained weights is just the original weights of YOLOv3

**Comment by AditTuf** [comment]
Hi, I was talking about "jichen_rmse_final.h5" weight file. But anyway I loaded the original weights file of YOLOv3 and trained the model. Getting good accuracy for object detection as well as distance estimation. Thanks !
